# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", type: "dhcp"

  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.provision "shell", inline: <<-SHELL

    sudo yum install -y epel-release
    sudo yum install -y nginx

    sudo systemctl start nginx
    sudo systemctl enable nginx

    mkdir -p ~/www-content
    echo "Hello, World!" > ~/www-content/index.html

    sudo chown -R nginx:nginx ~/www-content

    sudo rm -rf /usr/share/nginx/html
    sudo ln -s ~/www-content /usr/share/nginx/html
  SHELL
end